added data-dependent components
mmarganski/ztm pull request #3
Opened 2021-08-26 11:48 UTC by mmarganski

2021-08-26 12:16 UTC, gtarnopolski requested changes

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/Map.tsx
> +            ) : <></>}
there should be loader not empty space :D

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/MapView.tsx
> +        switch (currentTab){
)(space){

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/MapView.tsx
> +                return (<BusSelector/>)
enters

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/MapView.tsx
> +                return (<PlaceSelector isAddingAvailable />)
.

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/MapView.tsx
> +                return(<>
space after return
(
 <Fragment>
    JSX
 </Fragment>
)

don't use <></>, we don't use it because it's not clear

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/Markers.tsx
> +        <>
.

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/Markers.tsx
> +                            : process.env.REACT_APP_BUS_ICON}
icon is in envs?

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/PlaceSelector.tsx
> +        setPlace(prevPlaces => prevPlaces.filter(place => place.name !== name))
enter

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/PlaceSelector.tsx
> +            }))
.

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/PlaceSelector.tsx
> +            {isAddingAvailable && (<Button
.

2021-08-26 12:16 UTC, gtarnopolski commented on ztm-front/src/components/Sidebar.tsx
> +                        setCurrentTab(tabName)
redundant function body

2021-08-26 13:22 UTC, jpudysz requested changes

2021-08-26 13:22 UTC, jpudysz commented on ztm-front/src/components/Markers.tsx
> +            {(currentTab === TabsList.GF  ? [clickLatLng] : busPositions)
please don't use shortcuts. I know that's geofencing but for someone new GF may be a girlfriend

2021-08-26 13:22 UTC, jpudysz commented on ztm-front/src/components/PlaceSelector.tsx
> +                    text={'+'}
.

2021-08-26 13:22 UTC, jpudysz commented on ztm-front/src/hooks/stores/useBus.ts
> +import { useBusStore } from '../../stores'
.

2021-08-26 13:22 UTC, jpudysz commented on ztm-front/src/hooks/stores/useOthers.ts
> +import { useOthersStore } from '../../stores'
.

2021-08-26 13:22 UTC, jpudysz commented on ztm-front/src/hooks/stores/usePlaces.ts
> +import { usePlacesStore } from '../../stores'
.

2021-08-26 13:22 UTC, jpudysz commented on ztm-front/src/hooks/stores/useSocket.ts
> +import { useSocketStore } from '../../stores'
.

2021-08-26 13:27 UTC, gtarnopolski requested changes

2021-08-26 13:27 UTC, gtarnopolski commented on ztm-front/src/components/MapView.tsx
> +                    <div>
Fragment not div

2021-08-26 13:27 UTC, gtarnopolski commented on ztm-front/src/components/Map.tsx
> +  padding: 20%;
please don't use % parameters unsell it's width or height

2021-08-27 08:35 UTC, jpudysz requested changes

2021-08-27 08:35 UTC, jpudysz commented on ztm-front/src/components/ApiConnector.tsx
> +    const measureDistance = (position1: LatLng, position2: LatLng) => {
move it to utils

2021-08-27 08:41 UTC, jpudysz approved these changes

2021-08-27 11:38 UTC, merged